<h1 style="color:red">Numpy</h1>

**NumPy stands for Numerical Python.**
- It is a python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform and matrices.
- It was created in 2005 by Travis Oliphant.
- It is an open source project and can be used freely.
- Most powerful numerical processing library in Python . Array Oriented computing.
- Provides extensions package to python for multi-dimensional array
- very efficient 
- scientific computation

(Note: why numpy-> less Memory, less time, easy to use)

In [2]:
# To Install numpy run this command

# !pip install numpy 

In [3]:
# Creating a simple array in numpy:)
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# The array object in NumPy is called as ndarray,
# it provides a lot of supporting functions that make working with ndarray very easy.

In [5]:
l = [1, 2, 3, 4, 5, 6, 7]
arr = np.array(l)

print(type(l))
print(type(arr))
print("list:", l)   # list is comma separated
print("NP array:", arr)  # while ndarray not

<class 'list'>
<class 'numpy.ndarray'>
list: [1, 2, 3, 4, 5, 6, 7]
NP array: [1 2 3 4 5 6 7]


In [6]:
# arange()
arr = np.arange(10)

print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
# lets check efficiency/speed of list and ndarray

In [8]:
import time

t1 = time.time()
lst = list(range(1000000))
for i in range(1000000):
    lst[i] *= lst[i]
t2 = time.time()
print(t2-t1)

0.20762252807617188


In [9]:
t1 = time.time()
arr = np.arange(1000000)
arr = arr * arr
t2 = time.time()
print(t2-t1)


0.0038983821868896484


In [10]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr.ndim)
print(arr)

1
[1. 2. 3. 4. 5.]


In [11]:
# Print shape
print(arr.shape)

(5,)


In [12]:
# Print length
print(len(arr))

5


In [13]:
# Print Data type
print(arr.dtype)

float64


In [14]:
# Print item size in byte of each elements
print(arr.itemsize)

8


In [15]:
print(arr.size)

5


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)
print(np.diag(arr)) # print diagonal elements

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32
4
6
[1 5]


In [17]:
# Functions for creating arrays:)

arr = np.ones(10)  # by default it creates floating type array
print(arr)

arr = np.ones((3, 2), dtype=str)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[['1' '1']
 ['1' '1']
 ['1' '1']]


In [18]:
# zeros()

arr = np.zeros(10)
print(arr)

arr = np.zeros((2, 3), dtype=complex)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [19]:
# eye()

arr = np.eye(2,3)
print(arr)

print(np.eye(4, 8, dtype=int))

[[1. 0. 0.]
 [0. 1. 0.]]
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [20]:
# idenetity()

arr = np.identity(10) # it just accept rows no and type
print(arr.shape)
arr

(10, 10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# arange()

arr = np.arange(1, 10, 2, dtype=float) # start, step and type are optionals
arr

array([1., 3., 5., 7., 9.])

In [22]:
# arr = np.zeros

print(np.zeros(10))
print(np.zeros((10, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# def generate_sequence(n):
#     result = ""
#     i = 1
#     while len(result) < n:
#         result += str(i) * i # 1 + "2"*2
#         i += 1
#     return result[:n]  # Ensure the result is exactly n characters long

# # Example usage:
# n = 3
# while n:
#     print(generate_sequence(int(input())))
#     n-=1

<h3 style="color:springgreen">NumPy Random Numbers:)</h3>

1. **np.random.rand:** 
It generates an array with random numbers that are uniformly distributed between '0' and '1'.

2. **np.random.randn:**
It generates an array with random numbers that are normally distributed mean = 0 and stdev = 1 (standard derivation).

3. **np.random.randint:**
It generates an array with random numbers(integeres) that are uniformly distributed between '0' and given number.

4. **np.random.uniform:**
It generates an array with random numbers (float) between given numbers.

In [108]:
arr = np.random.rand(5)
print(arr)

[0.00657503 0.66133623 0.52403582 0.13169489 0.52443023]


In [26]:
print(np.random.rand(10, 2))

[[0.17553924 0.90908218]
 [0.04732111 0.33074319]
 [0.22855216 0.65932801]
 [0.36745382 0.31023466]
 [0.31542455 0.34476277]
 [0.07192443 0.62669277]
 [0.61229329 0.36818231]
 [0.26277813 0.12647085]
 [0.63583923 0.84426257]
 [0.45841137 0.44804421]]


In [27]:
print(np.random.randn(5))

[-0.22742342  0.04412264  0.82129639 -0.24266529 -0.1281654 ]


In [28]:
print(np.random.randn(5, 4))

[[ 1.06169591e+00  8.81708660e-01  1.43313914e-04  5.35068914e-01]
 [-8.62194332e-02  7.34112416e-01  1.07567682e+00 -1.40105839e+00]
 [-2.16667918e-01 -2.96177905e-01 -9.06555157e-02 -1.68449260e+00]
 [ 1.14673181e+00 -7.73590706e-02  9.81562207e-01  4.57448239e-01]
 [ 4.32786272e-02 -7.52481886e-02  9.49201353e-01  7.37229127e-01]]


In [29]:
# Random integer between '0' to '9'

print(np.random.randint(10))
print(np.random.randint(10, 78))

7
57


In [30]:
print(np.random.randint(10, size=(5, 4)))

[[7 1 8 7]
 [9 8 7 3]
 [8 6 4 2]
 [0 4 0 5]
 [6 7 1 5]]


In [31]:
print(np.random.randint(10, 40, size=(5, 4)))

[[35 14 35 36]
 [10 11 26 21]
 [20 34 28 16]
 [25 11 30 29]
 [20 23 37 39]]


In [32]:
print(np.random.uniform(10))

1.224150776783425


In [33]:
print(np.random.uniform(10, size=(5, 4)))

[[1.05993601 4.08262999 5.6489931  9.39999798]
 [2.52456465 2.23883864 2.96667921 8.38965132]
 [6.42911427 4.41591318 7.60820307 7.41535982]
 [5.27030015 8.19576167 2.84063663 4.0874073 ]
 [8.98576408 9.61212149 3.50719443 6.55134203]]


In [34]:
print(np.random.randint(10, 40, size = (5, 4)))

[[30 34 11 21]
 [20 35 12 26]
 [30 31 25 19]
 [29 20 34 19]
 [16 13 26 33]]


<h3 style="color:springgreen">NumPy Indexing:)</h3>
- The indexes in NumPy arrays start with '0' meaning that the first element has index '0' and the second has index '1' etc....


In [36]:
arr = 3*np.arange(10) # because of broadcasting 

print(arr)
print(arr[3])
print(arr[-1])

[ 0  3  6  9 12 15 18 21 24 27]
9
27


#### Accessing an index:
Syntax: arr[row_index, column_index]

In [38]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr[1, 2])

6


In [39]:
arr[1, 2] = 99
print(arr)

[[ 1  2  3]
 [ 4  5 99]]


In [40]:
# Note: NUMPY arrays are mutable

<h3 style="color:springgreen">NumPy Slicing:)</h3>

- Slicing means taking elements from one given index to another index.
- We pass slice instead of index as
    - [start : end]
- We define the step as [start: end: step]
- If we don't pass start it considered as '0' 
- If we don't pass end it is considered as length of array in that dimension.
- If we don't pass step it is considered as '1'.
- Syntax: arr[s:e:ss, s:e:ss]
    - s-start, e-end, ss- stepsize

In [43]:
arr = np.arange(10)

print(arr[::2])
print(arr[1:4])
print(arr[0:-4])

[0 2 4 6 8]
[1 2 3]
[0 1 2 3 4 5]


In [44]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

# print(arr)
print(arr[:2, 1:3])

[[2 3]
 [6 7]]


In [45]:
print(arr[1:2, :])

[[5 6 7 8]]


In [46]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

print(arr)

print(arr[2, 1])
print(arr[[0, 1, 2],[0, 1, 0]])

[[1 2]
 [3 4]
 [5 6]]
6
[1 4 5]


#### Numpy Maths:)

In [48]:
# Element wise operations:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Matrix Multiplications:

In [50]:
# Syntax: np.matmul or np.dot

In [51]:
print(np.matmul(x, y))

[[19 22]
 [43 50]]


In [52]:
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [53]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis = 0))  # column wise
print(np.sum(x, axis = 1))  # row wise

10
[4 6]
[3 7]


In [54]:
print(x)

[[1 2]
 [3 4]]


In [55]:
print(x.T)  # transpose

[[1 3]
 [2 4]]


In [56]:
np.exp(1)  # e^0 = 1; e^1 = 2.718 => 2. 72;

2.718281828459045

In [57]:
np.exp(2)  # e^2 = 2.72^2 => 7.389

7.38905609893065

<h3 style="color:springgreen">NumPy Statistics:)</h3>

1. Mean -> sum(n)/n
2. Median -> odd: (n+1)/2; even: n/2 + n/2 + 1
3. Mode -> This is not used
4. Standard derivation -> std = sqrt(variance)
5. Correlation coefficient 

In [60]:
x = np.array([160, 180, 146, 162, 184, 180])

print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

168.66666666666666
171.0
187.55555555555557
13.695092389449425


In [61]:
heights = np.array([160, 180, 146, 162, 184, 180])
weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

<h3 style="color:springgreen">NumPy Reshape:)</h3>

- Reshape means changing the shape of an array. 
- The shape of an array is the number of elements in each dimension.
- By reshaping, we can add or remove dimensions or change numbers of elements in each dimension.

In [64]:
arr = np.arange(0, 50, 5)

print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [65]:
arr2d = arr.reshape(2, 5)

print(arr2d)

[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [66]:
arr2d = arr.reshape(5, 2)

print(arr2d)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]


In [67]:
# arr2d = arr.reshape(3, 3)
# error -> can't reshape array of size 10 into shape(3, 3)

In [68]:
arr = np.arange(5, 50)

print(arr.shape)

(45,)


In [69]:
print(arr.reshape(5, 9))

[[ 5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49]]


In [70]:
print(arr.reshape(3, 3, 5))

[[[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


<h3 style="color:springgreen">Flatten:)</h3>

**This function return a copy of the array collapsed in one dimension.**
- If you modify the value of this array we can notice that the value of original array is not affected.
- Flatten() is comparatively slower than ravel() as it occupies memory.
- Flatten is a method of an ndarray object.

In [73]:
print(arr.flatten())

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<h3 style="color:springgreen">Linspace:)</h3>

- The linspace() funciton returns evenly spaced numbers over a specified interval [start : end]. The endpoint of the interval can optionally be excluded.
- Syntax: np.linspace(start, end, # of elements)

In [76]:
print(np.linspace(1, 10))  # by default returns 50 elements

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [77]:
print(np.linspace(10, 13, 6))

[10.  10.6 11.2 11.8 12.4 13. ]


<h3 style="color:springgreen">Sorting:)</h3>

**This function returns a sorted copy of an array**

In [80]:
arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[75 50 79 83 58 80 94 71 76 94]
 [99 71 67 57 63 70 80 82 50 72]
 [87 93 86 68 97 67 62 86 78 67]
 [59 94 78 90 64 59 87 54 52 71]
 [64 92 69 87 51 53 70 82 72 90]]


In [81]:
np.sort(arr, axis = 0) # column wise sorting

array([[59, 50, 67, 57, 51, 53, 62, 54, 50, 67],
       [64, 71, 69, 68, 58, 59, 70, 71, 52, 71],
       [75, 92, 78, 83, 63, 67, 80, 82, 72, 72],
       [87, 93, 79, 87, 64, 70, 87, 82, 76, 90],
       [99, 94, 86, 90, 97, 80, 94, 86, 78, 94]])

In [82]:
np.sort(arr, axis = 1) # row wise sorting

array([[50, 58, 71, 75, 76, 79, 80, 83, 94, 94],
       [50, 57, 63, 67, 70, 71, 72, 80, 82, 99],
       [62, 67, 67, 68, 78, 86, 86, 87, 93, 97],
       [52, 54, 59, 59, 64, 71, 78, 87, 90, 94],
       [51, 53, 64, 69, 70, 72, 82, 87, 90, 92]])

<h3 style="color:springgreen">Stacking:)</h3>

**This function is used to join  a sequence of same dimension arrays along a new axis.**
- The axis parameters specifies the index of the new axis in the dimesions of the result.
- for example:
    - If axis = 0; it will be the first dimension and 
    - if axis = -1 it will be the last dimension.
- Syntax; numpy.stack(arrays, axis)

In [85]:
arr1 = np.arange(5, 15).reshape(2, 5)

print(arr1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [86]:
arr2 = np.arange(25, 35).reshape(2, 5)

print(arr2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [87]:
np.vstack([arr1, arr2])  # vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [88]:
np.hstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

<h3 style="color:springgreen">Concatenate:)</h3>

**This functions concatenate a sequence of arrays along an existing axis.**

In [91]:
np.concatenate([arr1, arr2], axis = 0)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [92]:
np.concatenate([arr1, arr2], axis = 1)

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

<h3 style="color:springgreen">Append:)</h3>

**This appends values along the mentioned axis at the end of the array**

In [95]:
np.append(arr1, arr2, axis=1)

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

In [96]:
np.append(arr1, arr2, axis=0)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

<h3 style="color:springgreen">Where:)</h3>

**This funcions returns the indices of elements in an input array where the given condition is satisfied.**

In [99]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [100]:
# condition : array_like, bool
# Where True, yield `x`, otherwise yield `y`.

np.where(arr>64, 0, arr)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [101]:
np.where(arr>64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

In [102]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[1], [2]])

print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[1]
 [2]]


In [103]:
print(arr1 + arr2)

[[2 3]
 [5 6]]


In [104]:
arr3 = np.array([1, 2])

print(arr3)

[1 2]


In [105]:
print(arr1 + arr3)

[[2 4]
 [4 6]]


In [106]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr4)

[[1 2 3]
 [4 5 6]]


In [107]:
print(arr4 + arr3)

Error -> operands could not be 

SyntaxError: invalid syntax (1658409226.py, line 3)