<h3 style="color:springgreen;">Numpy Broadcasting</h3>

**The term broadcasting refers to the ablity of NumPy to treat arrays of different shapes during arithematic operations.**

- Arithematic operations on arrays are usually done on corresponding elements.
- If two arrays are of exactly the same shape, then these operations are smoothly performed.

**Broadcasting is possible if the following rules are satisfied:)**

- Array with smaller 'ndim' than the other is pretended with '1' on its shape.
- Size in each dimensions of the output shape is maximum of the input sizes in that dimension.
- An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
- If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

~ A set of arrays is said to be broadcastable it the above rules produce a valid result and one of the following is True:

- Arrays have exactly the same shape.
- Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
- Array having few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is True.
- Start matching the dimensions backword (Right to Left)
    - Compatible - If same number appears or if one of them is 1
    - Otherwise - Incompatable;


In [4]:
import numpy as np

In [5]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [6]:
#[[1 2 3]     [[1 2 3]      [[2 4 6]
# [1 2 3]]   + [1 2 3]]  =>  [5 7 9]]

In [7]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[1], [2]])

print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]


In [10]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([1, 2, 3, 4])

# Error - Operands couldn't broadcast together with shapes (5, ) (4, )
print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [11]:
arr_1 = np.array([[1], [2], [3], [4], [5]])
arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
